# -*- coding: utf-8 -*-
"""Tarea Redes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V2jpRaFmgBPn-f9kkI0pj0bJ1bHjuJh1
"""

import pandas as pd
Base = pd.read_csv('/content/presenciaredes.csv')

Followers_Enero = int (Base.iloc[7, 3])
Followers_Junio = int (Base.iloc[7, 8])

Diferencia_T = (Followers_Junio - Followers_Enero )
print( "Diferencia de Followers entre Enero y Junio:", Diferencia_T, "\n" )

print("Comparacion de visualizciones de Youtube \n")
print("Meses: \n Enero   : 1  \n Febrero : 2 \n Marzo   : 3 \n Abril   : 4   \n Mayo    : 5 \n Junio   : 6 ")
print("\nIntroduce el numero de los meses que quieras comparar")

print("Mes 1: ")
mes1 = int (input())
mes1 = (mes1 +2)

print("Mes 2: ")
mes2 = int (input())
mes2 = (mes2 +2)

Diferencia_Y = (mes1 - mes2 )
print( "\nDiferencia de Followers entre Yotube:", Diferencia_T, "\n" )


Valor_Pasado_F = float (Base.iloc[1, 3])
Valor_Presesnte_F = float (Base.iloc[1, 8])
Promedio_CF = round((((Valor_Presesnte_F - Valor_Pasado_F)/Valor_Pasado_F)*100),1)
print("Promedio de crecimiento de Facebook de enero a junio: ",Promedio_CF, "%" )

Valor_Pasado_T = float (Base.iloc[8, 3])
Valor_Presesnte_T = float (Base.iloc[8, 8])
Promedio_CT = round((((Valor_Presesnte_T - Valor_Pasado_T)/Valor_Pasado_T)*100),1)
print("Promedio de crecimiento de Twitter de enero a junio: ",Promedio_CT, "%" )